import { Award, Clock3, Flame, Orbit, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { AchievementCard } from '../components/AchievementCard';
import { PlanetRenderer } from '../components/PlanetRenderer';
import { getAchievements } from '../lib/achievements';
import { calculateStatistics } from '../lib/stats';
import { categories, type FocusSession } from '../types';

const dayNames = ['M', 'T', 'W', 'T', 'F', 'S', 'S'];

export function DashboardPage({ sessions }: { sessions: FocusSession[] }) {
  const stats = calculateStatistics(sessions); const achievements = getAchievements(sessions); const maxDay = Math.max(...stats.weeklyMinutes, 1);
  const recent = sessions.filter((s) => !s.demo).slice(0, 5);
  return <section className="page-shell py-12"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">A gentle look back</p><h1 className="section-title mt-3">Your progress</h1><p className="mt-2 text-slate-400">Every minute here is time you chose with intention.</p></div><Link className="button" to="/focus">Start a session</Link></div>
    <div className="mt-9 grid grid-cols-2 gap-3 lg:grid-cols-4">{[
      [Clock3, `${Math.floor(stats.totalMinutes / 60)}h ${stats.totalMinutes % 60}m`, 'Total focus'], [Orbit, String(stats.planets), 'Planets grown'], [Flame, `${stats.currentStreak} day${stats.currentStreak === 1 ? '' : 's'}`, 'Current rhythm'], [Award, `${achievements.filter((a) => a.unlocked).length}/${achievements.length}`, 'Discoveries'],
    ].map(([Icon, value, label]) => { const IconComponent = Icon as typeof Clock3; return <article className="glass-card p-5 sm:p-6" key={String(label)}><IconComponent size={19} className="text-mint" /><strong className="mt-5 block font-display text-2xl sm:text-3xl">{value as string}</strong><span className="mt-1 block text-sm text-slate-500">{label as string}</span></article>; })}</div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <article className="glass-card p-6"><div className="flex items-center justify-between"><div><h2 className="font-display text-xl font-bold">This week</h2><p className="mt-1 text-sm text-slate-500">Minutes focused each day</p></div><span className="text-sm font-semibold text-mint">{stats.weeklyMinutes.reduce((a, b) => a + b, 0)} min</span></div><div className="mt-8 flex h-48 items-end justify-around gap-3" role="img" aria-label={`Weekly focus minutes: ${stats.weeklyMinutes.join(', ')}`}>{stats.weeklyMinutes.map((value, index) => <div className="flex h-full flex-1 flex-col justify-end text-center" key={index}><span className="mb-2 text-xs text-slate-500">{value || ''}</span><div className="chart-bar mx-auto w-full max-w-10" style={{ height: `${Math.max(value ? 10 : 2, (value / maxDay) * 82)}%` }} /><span className="mt-3 text-xs text-slate-500">{dayNames[index]}</span></div>)}</div></article>
      <article className="glass-card p-6"><h2 className="font-display text-xl font-bold">Focus by category</h2><p className="mt-1 text-sm text-slate-500">Where your time has gone</p><div className="mt-6 space-y-4">{categories.map((category) => { const value = stats.byCategory[category]; const percentage = stats.totalMinutes ? value / stats.totalMinutes * 100 : 0; return <div key={category}><div className="flex justify-between text-sm"><span>{category}</span><span className="text-slate-500">{value} min</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-mint to-violet" style={{ width: `${percentage}%` }} /></div></div>; })}</div></article>
    </div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><article className="glass-card p-6"><h2 className="font-display text-xl font-bold">Recent missions</h2>{recent.length ? <div className="mt-4 divide-y divide-white/8">{recent.map((session) => <div className="flex items-center gap-3 py-3" key={session.id}><PlanetRenderer planet={session.planet} size={52} animate={false} /><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{session.taskName}</strong><span className="text-xs text-slate-500">{session.category} · {new Date(session.completedAt).toLocaleDateString()}</span></div><span className="text-sm text-slate-400">{session.durationMinutes}m</span></div>)}</div> : <div className="mt-8 text-center text-slate-500"><Sparkles className="mx-auto mb-3" />Your completed missions will appear here.</div>}</article>
      <article className="glass-card p-6"><h2 className="font-display text-xl font-bold">Rarest discovery</h2>{stats.rarestPlanet ? <div className="mt-2 flex items-center gap-5"><PlanetRenderer planet={stats.rarestPlanet} size={150} /><div><span className={`rarity rarity-${stats.rarestPlanet.rarity.toLowerCase()}`}>{stats.rarestPlanet.rarity}</span><h3 className="mt-3 font-display text-xl font-bold">{stats.rarestPlanet.name}</h3><p className="mt-1 text-sm text-slate-500">A special world in your collection.</p></div></div> : <p className="mt-8 text-slate-500">Your first discovery is still out there.</p>}</article></div>
    <div className="mt-12"><div className="flex items-end justify-between"><div><p className="eyebrow">Milestones, not pressure</p><h2 className="mt-3 font-display text-2xl font-bold">Achievements</h2></div><span className="text-sm text-slate-500">Longest rhythm: {stats.longestStreak} days</span></div><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{achievements.map((achievement) => <AchievementCard achievement={achievement} key={achievement.id} />)}</div></div>
  </div></section>;
}
